# Generated by Django 2.1.7 on 2019-03-04 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(default='none', max_length=20)),
                ('created_date', models.DateTimeField(verbose_name='created_date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname_text', models.CharField(default='anonymous', max_length=20)),
                ('created_date', models.DateTimeField(verbose_name='created_date')),
                ('is_owner', models.BooleanField(default=False)),
                ('auth_name', models.CharField(default='anonymous', max_length=20)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Chatroom')),
            ],
        ),
    ]
