# Generated by Django 2.1.7 on 2019-03-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngreDesc',
            fields=[
                ('desc_id', models.CharField(default='TBD', max_length=1200, primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(default='TBD', max_length=1200)),
                ('translate_status', models.CharField(default='TBD', max_length=1200)),
                ('one_liner', models.CharField(default='TBD', max_length=1200)),
                ('one_liner_kr', models.CharField(default='TBD', max_length=1200)),
                ('bottom_line_en', models.CharField(default='TBD', max_length=12000)),
                ('bottom_line_kr', models.CharField(default='TBD', max_length=12000)),
                ('upside_en', models.CharField(default='TBD', max_length=12000)),
                ('upside_kr', models.CharField(default='TBD', max_length=12000)),
                ('downside_en', models.CharField(default='TBD', max_length=12000)),
                ('downside_kr', models.CharField(default='TBD', max_length=12000)),
                ('mechnism_en', models.CharField(default='TBD', max_length=12000)),
                ('mechnism_kr', models.CharField(default='TBD', max_length=12000)),
                ('pharmacist_tips', models.CharField(default='TBD', max_length=12000)),
                ('pharmacist_tips_kr', models.CharField(default='TBD', max_length=12000)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ing_code', models.CharField(default='TBD', max_length=1200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='IngreForm',
            fields=[
                ('ing_form_id', models.CharField(default='TBD', max_length=1200, primary_key=True, serialize=False)),
                ('ing_name_eng', models.CharField(default='TBD', max_length=1200)),
                ('ing_name_kr', models.CharField(default='TBD', max_length=1200)),
                ('form', models.CharField(default='TBD', max_length=1200)),
                ('desc_id', models.CharField(default='TBD', max_length=1200)),
                ('note', models.CharField(default='TBD', max_length=1200)),
                ('ing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='drug.IngreDesc')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_code', models.CharField(default='TBD', max_length=1200, primary_key=True, serialize=False)),
                ('ing_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='drug.Ingredient')),
            ],
            options={
                'ordering': ['prod_code'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('reg_code', models.CharField(default='TBD', max_length=1200, primary_key=True, serialize=False)),
                ('ing_code', models.CharField(default='TBD', max_length=1200)),
                ('drug_name', models.CharField(default='TBD', max_length=12000)),
                ('drug_class', models.CharField(default='TBD', max_length=1200)),
                ('storage', models.CharField(default='TBD', max_length=1200)),
                ('exp_date', models.CharField(default='TBD', max_length=1200)),
                ('attach', models.CharField(default='TBD', max_length=12000)),
                ('look', models.CharField(default='TBD', max_length=12000)),
                ('manufac_id', models.CharField(default='TBD', max_length=1200)),
                ('manufacturer', models.CharField(default='TBD', max_length=1200)),
                ('img_file', models.CharField(default='TBD', max_length=1200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reg_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='drug.Registration'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ing_form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingres', to='drug.IngreForm'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('reg_code', 'prod_code')},
        ),
    ]
