# Generated by Django 2.1.7 on 2019-03-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredesc',
            name='bottom_line_en',
            field=models.CharField(default='TBD', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='bottom_line_kr',
            field=models.CharField(default='TBD', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='desc_id',
            field=models.CharField(default='TBD', max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='downside_en',
            field=models.CharField(default='TBD', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='downside_kr',
            field=models.CharField(default='TBD', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='ingredient_name',
            field=models.CharField(default='TBD', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='mechnism_en',
            field=models.CharField(default='TBD', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='mechnism_kr',
            field=models.CharField(default='TBD', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='one_liner',
            field=models.CharField(default='TBD', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='one_liner_kr',
            field=models.CharField(default='TBD', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='pharmacist_tips',
            field=models.CharField(default='TBD', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='pharmacist_tips_kr',
            field=models.CharField(default='TBD', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='translate_status',
            field=models.CharField(default='TBD', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='upside_en',
            field=models.CharField(default='TBD', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='upside_kr',
            field=models.CharField(default='TBD', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingreform',
            name='form',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingreform',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='registration',
            name='drug_class',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='registration',
            name='drug_name',
            field=models.CharField(max_length=1000),
        ),
    ]
