# Generated by Django 2.1.7 on 2019-03-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredesc',
            name='desc_id',
            field=models.CharField(default='TBD', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ing_code',
            field=models.CharField(default='TBD', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingreform',
            name='ing_form_id',
            field=models.CharField(default='TBD', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='durcode1',
            field=models.CharField(default='TBD', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='durcode2',
            field=models.CharField(default='TBD', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='durcode3',
            field=models.CharField(default='TBD', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='durcode4',
            field=models.CharField(default='TBD', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_code',
            field=models.CharField(default='TBD', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_code',
            field=models.CharField(default='TBD', max_length=10, primary_key=True, serialize=False),
        ),
    ]
