# Generated by Django 2.1.7 on 2019-03-07 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_auto_20190307_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ing_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ing', to='drug.Ingredient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reg_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_regi', to='drug.Registration'),
        ),
    ]
