# Generated by Django 2.1.7 on 2019-03-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_auto_20190307_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
