# Generated by Django 2.1.7 on 2019-03-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0003_auto_20190301_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredesc',
            name='bottom_line_en',
            field=models.CharField(default='TBD', max_length=10000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='bottom_line_kr',
            field=models.CharField(default='TBD', max_length=10000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='downside_en',
            field=models.CharField(default='TBD', max_length=10000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='downside_kr',
            field=models.CharField(default='TBD', max_length=10000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='mechnism_en',
            field=models.CharField(default='TBD', max_length=10000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='mechnism_kr',
            field=models.CharField(default='TBD', max_length=10000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='pharmacist_tips',
            field=models.CharField(default='TBD', max_length=10000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='pharmacist_tips_kr',
            field=models.CharField(default='TBD', max_length=10000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='upside_en',
            field=models.CharField(default='TBD', max_length=10000),
        ),
        migrations.AlterField(
            model_name='ingredesc',
            name='upside_kr',
            field=models.CharField(default='TBD', max_length=10000),
        ),
    ]
