# Generated by Django 2.1.7 on 2019-03-09 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0003_auto_20190309_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ing_form_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingres', to='drug.IngreForm'),
        ),
        migrations.AlterField(
            model_name='ingreform',
            name='ing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='drug.IngreDesc'),
        ),
    ]
