# Generated by Django 2.1.7 on 2019-03-07 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0003_auto_20190307_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['prod_code']},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ing_form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_form', to='drug.IngreForm'),
        ),
        migrations.AlterField(
            model_name='ingreform',
            name='ing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_desc', to='drug.IngreDesc'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('reg_code', 'prod_code')},
        ),
    ]
