# Generated by Django 2.1.7 on 2019-03-07 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0004_auto_20190307_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ing_form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingres', to='drug.IngreForm'),
        ),
        migrations.AlterField(
            model_name='ingreform',
            name='ing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='drug.IngreDesc'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ing_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='drug.Ingredient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reg_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='drug.Registration'),
        ),
    ]
