# Generated by Django 2.1.7 on 2019-04-17 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('one_liner', models.CharField(blank=True, default='', max_length=600)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('rep_code', models.CharField(default='', max_length=100)),
                ('is_rep', models.BooleanField(default=False)),
                ('name_kr', models.CharField(db_index=True, default='', max_length=600)),
                ('name_en', models.CharField(blank=True, default='', max_length=600)),
            ],
            options={
                'verbose_name': '질병',
                'verbose_name_plural': '질병 목록',
            },
        ),
        migrations.CreateModel(
            name='DiseaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('one_liner', models.CharField(blank=True, default='', max_length=600)),
                ('source', models.CharField(blank=True, default='', max_length=300)),
                ('rep_title', models.CharField(blank=True, default='', max_length=300)),
                ('rep_title_en', models.CharField(blank=True, default='', max_length=300)),
                ('pcare_desc', models.TextField(blank=True, null=True)),
                ('pcare_desc_en', models.TextField(blank=True, null=True)),
                ('idx', models.IntegerField(blank=True, null=True)),
                ('title1', models.CharField(blank=True, max_length=300, null=True)),
                ('desc1', models.TextField(blank=True, null=True)),
                ('title2', models.CharField(blank=True, max_length=300, null=True)),
                ('desc2', models.TextField(blank=True, null=True)),
                ('title3', models.CharField(blank=True, max_length=300, null=True)),
                ('desc3', models.TextField(blank=True, null=True)),
                ('title4', models.CharField(blank=True, max_length=300, null=True)),
                ('desc4', models.TextField(blank=True, null=True)),
                ('title5', models.CharField(blank=True, max_length=300, null=True)),
                ('desc5', models.TextField(blank=True, null=True)),
                ('title6', models.CharField(blank=True, max_length=300, null=True)),
                ('desc6', models.TextField(blank=True, null=True)),
                ('title7', models.CharField(blank=True, max_length=300, null=True)),
                ('desc7', models.TextField(blank=True, null=True)),
                ('title8', models.CharField(blank=True, max_length=300, null=True)),
                ('desc8', models.TextField(blank=True, null=True)),
                ('title9', models.CharField(blank=True, max_length=300, null=True)),
                ('desc9', models.TextField(blank=True, null=True)),
                ('title10', models.CharField(blank=True, max_length=300, null=True)),
                ('desc10', models.TextField(blank=True, null=True)),
                ('translate_flag', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': '질병 설명',
                'verbose_name_plural': '질병 설명 목록',
            },
        ),
        migrations.CreateModel(
            name='DiseaseDetailDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('div_name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': '질병 설명 분류',
                'verbose_name_plural': '질병 설명 분류 목록',
            },
        ),
        migrations.AddField(
            model_name='diseasedetail',
            name='disease_detail_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disease.DiseaseDetailDivision'),
        ),
        migrations.AddField(
            model_name='disease',
            name='diseaseDetail',
            field=models.ManyToManyField(blank=True, related_name='diseases', to='disease.DiseaseDetail'),
        ),
    ]
