# Generated by Django 2.1.7 on 2019-03-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfilemodel',
            name='title',
        ),
    ]
