# Generated by Django 2.1.7 on 2019-03-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_remove_uploadfilemodel_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFileModel',
        ),
    ]
